/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.MedecinDAO;
import Pharmacie.DAO.PatientDAO;
import Pharmacie.DAO.PrescriptionDAO;
import Pharmacie.Metier.Medecins;
import Pharmacie.Metier.Patients;
import Pharmacie.Metier.Prescriptions;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.time.LocalDate;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author meril
 */
public class CreationPres extends javax.swing.JPanel{

    MedecinDAO medDAO =null;
    PrescriptionDAO presDAO=null;
    Prescriptions pres=null;
    DefaultComboBoxModel dlm = new DefaultComboBoxModel();
    DefaultComboBoxModel dlp = new DefaultComboBoxModel();
    List<Medecins> med;
    PatientDAO patDAO=null;
    List<Patients> pat;
    
    
    public void setPrescriptionDAO(PrescriptionDAO presDAO){
        this.presDAO=presDAO;
    }
    
    public void setPatientDAO(PatientDAO patDAO){
        this.patDAO= patDAO;
    }
    
    public void setMedecinDAO(MedecinDAO medDAO){
        this.medDAO=medDAO;
    }
    /**
     * Creates new form CreationPres
     */
    public CreationPres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidpres = new javax.swing.JLabel();
        txtidpres = new javax.swing.JTextField();
        lbldatepres = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btcreationPres = new javax.swing.JButton();
        jdatepres = new com.toedter.calendar.JDateChooser();
        jComboMedecin = new javax.swing.JComboBox<>();
        jComboPatient = new javax.swing.JComboBox<>();

        lblidpres.setText("  Identifiant de la prescription");

        txtidpres.setEditable(false);

        lbldatepres.setText("  Date de la prescription");

        jLabel1.setText("  Identifiant du medecin prescripteur");

        jLabel2.setText("  Identifiant du patient");

        btcreationPres.setText("   Créer");
        btcreationPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreationPresActionPerformed(evt);
            }
        });

        jdatepres.setDateFormatString("dd-MM-yyyy");
        jdatepres.setFocusCycleRoot(true);
        jdatepres.setName("jdatepres"); // NOI18N

        jComboMedecin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblidpres, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldatepres, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidpres)
                            .addComponent(jdatepres, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jComboMedecin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btcreationPres, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidpres, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidpres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldatepres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdatepres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btcreationPres)
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void inject_patient() {
        try {
            pat=patDAO.AfficPat();
            //System.out.println(pat);
            if(jComboPatient!=null){
                jComboPatient.removeAllItems();
            }
            //test utilisation des iterateurs
            Iterator<Patients> itpat=pat.iterator();
            while(itpat.hasNext()){
                Patients patient=itpat.next();
                dlp.addElement(patient.toString());
            }
            //test utilisation boucle for
            /*for (int i = 0; i < pat.size(); i++) {
                dlp.addElement(pat.get(i).toString());
 
            }*/
            jComboPatient.setModel(dlp);
 
        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }
    }
    
    //jComboMedecin;
    //private javax.swing.JComboBox<String> jComboPatient
    public void inject_medecin() {
        try {
            med=medDAO.afficher();
            //System.out.println(med);
            if(jComboMedecin!=null){
                jComboMedecin.removeAllItems();
            }
            Iterator<Medecins> itmed=med.iterator();
            while(itmed.hasNext()){
                Medecins medecin=itmed.next();
                dlm.addElement(medecin.toString());
            }
            
            /*for (int i = 0; i < med.size(); i++) {
                dlm.addElement(med.get(i).toString());
 
            }*/
            jComboMedecin.setModel(dlm);
 
        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }
    }
    
    private void btcreationPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreationPresActionPerformed
     
        try{
         
        String date=((JTextField)jdatepres.getDateEditor().getUiComponent()).getText();
         int jour=Integer.parseInt(date.substring(0,2));
         int mois=Integer.parseInt(date.substring(4,5));
         int an=Integer.parseInt(date.substring(6));
            System.out.println(date);
            System.out.println(an+" "+mois+" "+jour);
        LocalDate datepres=LocalDate.of(an, mois,jour);
        
        int position=jComboMedecin.getSelectedIndex();
        Medecins medecin=med.get(position);
        //int idmedecin=med.get(position).getIdmed();
        
        int x=jComboPatient.getSelectedIndex();
        Patients patient=pat.get(x);
        //int idpat=pat.get(x).getIdpat();
        
        pres= new Prescriptions(0,datepres,medecin.getIdmed(),patient.getIdpat());
        pres = presDAO.create(pres);
        txtidpres.setText(""+pres.getIdpres());
            JOptionPane.showMessageDialog(this,"Prescription créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR CREATION Prescription",JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btcreationPresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreationPres;
    private javax.swing.JComboBox<String> jComboMedecin;
    private javax.swing.JComboBox<String> jComboPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jdatepres;
    private javax.swing.JLabel lbldatepres;
    private javax.swing.JLabel lblidpres;
    private javax.swing.JTextField txtidpres;
    // End of variables declaration//GEN-END:variables
}
