/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.PrescriptionDAO;
import Pharmacie.Metier.Prescriptions;
import connections.DBConnection;
import java.sql.Connection;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.temporal.TemporalAccessor;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdk.nashorn.internal.objects.NativeString.substr;

/**
 *
 * @author meril
 */
public class CreationPres extends javax.swing.JPanel{

    
    PrescriptionDAO presDAO=null;
    
    
    public void setPrescriptionDAO(PrescriptionDAO presDAO){
        this.presDAO=presDAO;
    }
    
    
    /**
     * Creates new form CreationPres
     */
    public CreationPres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidpres = new javax.swing.JLabel();
        txtidpres = new javax.swing.JTextField();
        lbldatepres = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtmedpres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtidpatpres = new javax.swing.JTextField();
        btcreationPres = new javax.swing.JButton();
        jdatepres = new com.toedter.calendar.JDateChooser();

        lblidpres.setText("  Identifiant de la prescription");

        txtidpres.setEditable(false);

        lbldatepres.setText("  Date de la prescription");

        jLabel1.setText("  Identifiant du medecin prescripteur");

        jLabel2.setText("  Identifiant du patient");

        btcreationPres.setText("   Créer");
        btcreationPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreationPresActionPerformed(evt);
            }
        });

        jdatepres.setDateFormatString("dd/MM/yy");
        jdatepres.setDoubleBuffered(false);
        jdatepres.setName("jdatepres"); // NOI18N
        jdatepres.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblidpres, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldatepres, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidpatpres)
                            .addComponent(txtidpres)
                            .addComponent(txtmedpres)
                            .addComponent(jdatepres, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btcreationPres, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidpres, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidpres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldatepres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdatepres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmedpres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidpatpres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btcreationPres)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btcreationPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreationPresActionPerformed
     
        try{
         
        String date=((JTextField)jdatepres.getDateEditor().getUiComponent()).getText();
         int jour=Integer.parseInt(date.substring(1,2));
         int mois=Integer.parseInt(date.substring(4,5));
         int an=Integer.parseInt(date.substring(6));
         
        LocalDate datepres=LocalDate.of(an, mois,jour);
        
        int idmedecin=Integer.parseInt(txtmedpres.getText());
        int idpat=Integer.parseInt(txtidpatpres.getText());
        Prescriptions pres= new Prescriptions(0,datepres,idmedecin,idpat);
        pres = presDAO.create(pres);
        txtidpres.setText(""+pres.getIdpres());
            JOptionPane.showMessageDialog(this,"Prescription créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btcreationPresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreationPres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JDateChooser jdatepres;
    private javax.swing.JLabel lbldatepres;
    private javax.swing.JLabel lblidpres;
    private javax.swing.JTextField txtidpatpres;
    private javax.swing.JTextField txtidpres;
    private javax.swing.JTextField txtmedpres;
    // End of variables declaration//GEN-END:variables
}
