/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.MedicamentDAO;
import Pharmacie.Metier.Medicaments;
import javax.swing.JOptionPane;

/**
 *
 * @author meril
 */
public class CreationMedicaments extends javax.swing.JPanel {

    MedicamentDAO medicDAO=null;
    
    public void setMedicamentDAO(MedicamentDAO medicDAO){
        this.medicDAO=medicDAO;
    }
    /**
     * Creates new form CreationMedicaments
     */
    public CreationMedicaments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidmedic = new javax.swing.JLabel();
        lblnommedic = new javax.swing.JLabel();
        lbldescmedic = new javax.swing.JLabel();
        lblcodemedic = new javax.swing.JLabel();
        btcreamedic = new javax.swing.JButton();
        txtidmedic = new javax.swing.JTextField();
        txtnommedic = new javax.swing.JTextField();
        txtdescmedic = new javax.swing.JTextField();
        txtcodemedic = new javax.swing.JTextField();

        lblidmedic.setText("  Identifiant du medicament");

        lblnommedic.setText("  Nom du medicament");

        lbldescmedic.setText("  Description du medicament");

        lblcodemedic.setText("  Code du medicament");

        btcreamedic.setText("  Création");
        btcreamedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcreamedicActionPerformed(evt);
            }
        });

        txtidmedic.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidmedic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnommedic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbldescmedic, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(lblcodemedic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidmedic)
                                    .addComponent(txtnommedic, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdescmedic)
                                    .addComponent(txtcodemedic, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(btcreamedic)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidmedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnommedic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnommedic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldescmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btcreamedic)
                .addGap(95, 95, 95))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btcreamedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcreamedicActionPerformed
        try{
            String nom=txtnommedic.getText();
            String description=txtdescmedic.getText();
            String code=txtcodemedic.getText();
            Medicaments medics=new Medicaments(0,nom,description,code);
            medics=medicDAO.create(medics);
            txtidmedic.setText(""+medics.getIdmed());
            JOptionPane.showMessageDialog(this,"Medicament créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btcreamedicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcreamedic;
    private javax.swing.JLabel lblcodemedic;
    private javax.swing.JLabel lbldescmedic;
    private javax.swing.JLabel lblidmedic;
    private javax.swing.JLabel lblnommedic;
    private javax.swing.JTextField txtcodemedic;
    private javax.swing.JTextField txtdescmedic;
    private javax.swing.JTextField txtidmedic;
    private javax.swing.JTextField txtnommedic;
    // End of variables declaration//GEN-END:variables
}
