/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.MedecinDAO;
import Pharmacie.Metier.Medecins;
import javax.swing.JOptionPane;

/**
 *
 * @author meril
 */
public class CreationMedecin extends javax.swing.JPanel {

    MedecinDAO medecinDAO=null;
    
    public void setMedecinDAO(MedecinDAO medDAO){
        this.medecinDAO=medDAO;
    }
    /**
     * Creates new form CreationMedecin
     */
    public CreationMedecin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidmedecin = new javax.swing.JLabel();
        lblmatricule = new javax.swing.JLabel();
        lblnommedecin = new javax.swing.JLabel();
        lblprenommedecin = new javax.swing.JLabel();
        lbltelmedecin = new javax.swing.JLabel();
        txtidmedecin = new javax.swing.JTextField();
        txtmatriculemedecin = new javax.swing.JTextField();
        txtnommedecin = new javax.swing.JTextField();
        txtprenommedecin = new javax.swing.JTextField();
        txttelmedecin = new javax.swing.JTextField();
        btCreateMed = new javax.swing.JButton();

        lblidmedecin.setText("  Identifiant du medecin");

        lblmatricule.setText("  Matricule du medecin");

        lblnommedecin.setText("  Nom du medecin");

        lblprenommedecin.setText("  Prenom du medecin");

        lbltelmedecin.setText("  Telephone ");

        txtidmedecin.setEditable(false);

        btCreateMed.setText("  Création");
        btCreateMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateMedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidmedecin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmatricule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblnommedecin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprenommedecin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltelmedecin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidmedecin, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txtmatriculemedecin)
                            .addComponent(txtnommedecin)
                            .addComponent(txtprenommedecin)
                            .addComponent(txttelmedecin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(btCreateMed)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidmedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidmedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmatriculemedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnommedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnommedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprenommedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenommedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltelmedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelmedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btCreateMed)
                .addGap(58, 58, 58))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCreateMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateMedActionPerformed
        try{
            String matricule=txtmatriculemedecin.getText();
            String nom=txtnommedecin.getText();
            String prenom=txtprenommedecin.getText();
            String tel=txttelmedecin.getText();
            Medecins meds=new Medecins(0,matricule,nom,prenom,tel);
            meds=medecinDAO.create(meds);
            txtidmedecin.setText(""+meds.getIdmed());
            JOptionPane.showMessageDialog(this,"Medicament créé","succès",JOptionPane.INFORMATION_MESSAGE);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btCreateMedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreateMed;
    private javax.swing.JLabel lblidmedecin;
    private javax.swing.JLabel lblmatricule;
    private javax.swing.JLabel lblnommedecin;
    private javax.swing.JLabel lblprenommedecin;
    private javax.swing.JLabel lbltelmedecin;
    private javax.swing.JTextField txtidmedecin;
    private javax.swing.JTextField txtmatriculemedecin;
    private javax.swing.JTextField txtnommedecin;
    private javax.swing.JTextField txtprenommedecin;
    private javax.swing.JTextField txttelmedecin;
    // End of variables declaration//GEN-END:variables
}
