/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.PatientDAO;
import Pharmacie.DAO.PrescriptionDAO;
import connections.DBConnection;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author meril
 */
public class GestionPatient extends javax.swing.JFrame {

    CardLayout cardl;
    /**
     * Creates new form GestionPatient
     */
    public GestionPatient() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        
      PatientDAO patDAO= new PatientDAO();
      PrescriptionDAO presDAO= new PrescriptionDAO();
      patDAO.setDbConnect(dbConnect);
      creation1.setPatientDAO(patDAO);
      rechExact1.setPatientDAO(patDAO);
      rechExact1.setPrescriptionDAO(presDAO);
      rechPart1.setPatientDAO(patDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creation1 = new Pharmacie.graph.Creation();
        rechPart1 = new Pharmacie.graph.RechPart();
        rechExact1 = new Pharmacie.graph.RechExact();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPat = new javax.swing.JMenu();
        itemCrea = new javax.swing.JMenuItem();
        RechExacte = new javax.swing.JMenuItem();
        RechPartiellle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(creation1, "cardCreaPat");
        getContentPane().add(rechPart1, "cardRechNomPat");
        getContentPane().add(rechExact1, "cardRechNumPat");

        MenuPat.setText("Patient");
        MenuPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPatActionPerformed(evt);
            }
        });

        itemCrea.setText("Créer Patient");
        itemCrea.setOpaque(true);
        itemCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreaActionPerformed(evt);
            }
        });
        MenuPat.add(itemCrea);

        RechExacte.setText("Recherche Numero Patient");
        RechExacte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechExacteActionPerformed(evt);
            }
        });
        MenuPat.add(RechExacte);

        RechPartiellle.setText("Recherche Partielle Patient");
        RechPartiellle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechPartiellleActionPerformed(evt);
            }
        });
        MenuPat.add(RechPartiellle);

        jMenuBar1.add(MenuPat);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreaActionPerformed
        cardl.show(this.getContentPane(), "cardCreaPat");
    }//GEN-LAST:event_itemCreaActionPerformed

    private void RechExacteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechExacteActionPerformed
         cardl.show(this.getContentPane(), "cardRechNumPat");
    }//GEN-LAST:event_RechExacteActionPerformed

    private void RechPartiellleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechPartiellleActionPerformed
        cardl.show(this.getContentPane(), "cardRechNomPat");
    }//GEN-LAST:event_RechPartiellleActionPerformed

    private void MenuPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuPatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuPat;
    private javax.swing.JMenuItem RechExacte;
    private javax.swing.JMenuItem RechPartiellle;
    private Pharmacie.graph.Creation creation1;
    private javax.swing.JMenuItem itemCrea;
    private javax.swing.JMenuBar jMenuBar1;
    private Pharmacie.graph.RechExact rechExact1;
    private Pharmacie.graph.RechPart rechPart1;
    // End of variables declaration//GEN-END:variables
}
