/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.MedecinDAO;
import Pharmacie.DAO.PatientDAO;
import Pharmacie.DAO.PrescriptionDAO;
import connections.DBConnection;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author meril
 */
public class GestionPrescription extends javax.swing.JFrame {

    CardLayout cardl;
    /**
     * Creates new form GestionPrescription
     */
    public GestionPrescription() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
      PrescriptionDAO presDAO= new PrescriptionDAO();
      presDAO.setDbConnect(dbConnect);
      
      PatientDAO patDAO = new PatientDAO();
      patDAO.setDbConnect(dbConnect);
      
      MedecinDAO medDAO = new MedecinDAO();
      medDAO.setDbConnect(dbConnect);
      
      creationPres1.setPrescriptionDAO(presDAO);
      creationPres1.setMedecinDAO(medDAO);
      creationPres1.setPatientDAO(patDAO);
      rechPres1.setPrescriptionDAO(presDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creationPres1 = new Pharmacie.graph.CreationPres();
        rechPres1 = new Pharmacie.graph.RechPres();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPres = new javax.swing.JMenu();
        itemCreaPres = new javax.swing.JMenuItem();
        itemrechPres = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(creationPres1, "cardCreaPres");
        getContentPane().add(rechPres1, "cardRechPres");
        rechPres1.getAccessibleContext().setAccessibleDescription("");

        MenuPres.setText("Prescription");

        itemCreaPres.setText("Creation Prescription");
        itemCreaPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreaPresActionPerformed(evt);
            }
        });
        MenuPres.add(itemCreaPres);

        itemrechPres.setText("Recherche Prescription");
        itemrechPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemrechPresActionPerformed(evt);
            }
        });
        MenuPres.add(itemrechPres);

        jMenuBar1.add(MenuPres);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreaPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreaPresActionPerformed
        cardl.show(this.getContentPane(), "cardCreaPres");
    }//GEN-LAST:event_itemCreaPresActionPerformed

    private void itemrechPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemrechPresActionPerformed
        cardl.show(this.getContentPane(), "cardRechPres");
    }//GEN-LAST:event_itemrechPresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPrescription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GestionPrescription().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuPres;
    private Pharmacie.graph.CreationPres creationPres1;
    private javax.swing.JMenuItem itemCreaPres;
    private javax.swing.JMenuItem itemrechPres;
    private javax.swing.JMenuBar jMenuBar1;
    private Pharmacie.graph.RechPres rechPres1;
    // End of variables declaration//GEN-END:variables
}
