/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.PatientDAO;
import Pharmacie.DAO.PrescriptionDAO;
import connections.DBConnection;
import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author meril
 */
public class Gestion_Pharmacie extends javax.swing.JFrame {

    CardLayout cardl;
    /**
     * Creates new form Gestion_Pharmacie
     */
    public Gestion_Pharmacie() {
        initComponents();
        cardl=(CardLayout)this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connection invalide");
            JOptionPane.showMessageDialog(this,"connexion invalide","ERREUR",JOptionPane.ERROR_MESSAGE);
        }
        PatientDAO patDAO=new PatientDAO();
       patDAO.setDbConnect(dbConnect);
       PrescriptionDAO presDAO= new PrescriptionDAO();
      presDAO.setDbConnect(dbConnect);
      creationPres1.setPrescriptionDAO(presDAO);
      rechPres1.setPrescriptionDAO(presDAO);
      creation1.setPatientDAO(patDAO);
      rechExact1.setPatientDAO(patDAO);
      rechPart1.setPatientDAO(patDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        font1 = new Pharmacie.graph.font();
        creation1 = new Pharmacie.graph.Creation();
        creationPres1 = new Pharmacie.graph.CreationPres();
        rechExact1 = new Pharmacie.graph.RechExact();
        rechPart1 = new Pharmacie.graph.RechPart();
        rechPres1 = new Pharmacie.graph.RechPres();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAccueil = new javax.swing.JMenu();
        itemAccueil = new javax.swing.JMenuItem();
        menuPat = new javax.swing.JMenu();
        itemCreaPat = new javax.swing.JMenuItem();
        RechExacte = new javax.swing.JMenuItem();
        RechPartielle = new javax.swing.JMenuItem();
        menuPres = new javax.swing.JMenu();
        itemCreaPres = new javax.swing.JMenuItem();
        itemRechPres = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(font1, "cardAccueil");
        getContentPane().add(creation1, "cardCreaPat");
        getContentPane().add(creationPres1, "cardCreationPres");
        getContentPane().add(rechExact1, "cardRechExacte");
        getContentPane().add(rechPart1, "cardRechPart");
        getContentPane().add(rechPres1, "cardRechPres");

        menuAccueil.setText("Accueil");
        menuAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAccueilActionPerformed(evt);
            }
        });

        itemAccueil.setText("Accueil Pharmacie");
        itemAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAccueilActionPerformed(evt);
            }
        });
        menuAccueil.add(itemAccueil);

        jMenuBar1.add(menuAccueil);

        menuPat.setText("Patients");

        itemCreaPat.setText("Creation Patient");
        itemCreaPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreaPatActionPerformed(evt);
            }
        });
        menuPat.add(itemCreaPat);

        RechExacte.setText("Recherche Numero Patient");
        RechExacte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechExacteActionPerformed(evt);
            }
        });
        menuPat.add(RechExacte);

        RechPartielle.setText("Recherche partielle patient");
        RechPartielle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechPartielleActionPerformed(evt);
            }
        });
        menuPat.add(RechPartielle);

        jMenuBar1.add(menuPat);

        menuPres.setText("Prescriptions");

        itemCreaPres.setText("Creation  prescription");
        itemCreaPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreaPresActionPerformed(evt);
            }
        });
        menuPres.add(itemCreaPres);

        itemRechPres.setText("Recherche prescription");
        itemRechPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechPresActionPerformed(evt);
            }
        });
        menuPres.add(itemRechPres);

        jMenuBar1.add(menuPres);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreaPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreaPatActionPerformed
        cardl.show(this.getContentPane(),"cardCreaPat");
    }//GEN-LAST:event_itemCreaPatActionPerformed

    private void RechExacteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechExacteActionPerformed
        cardl.show(this.getContentPane(),"cardRechExacte");
    }//GEN-LAST:event_RechExacteActionPerformed

    private void RechPartielleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechPartielleActionPerformed
        cardl.show(this.getContentPane(),"cardRechPart");
    }//GEN-LAST:event_RechPartielleActionPerformed

    private void itemCreaPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreaPresActionPerformed
         cardl.show(this.getContentPane(),"cardCreationPres");
    }//GEN-LAST:event_itemCreaPresActionPerformed

    private void itemRechPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechPresActionPerformed
        cardl.show(this.getContentPane(),"cardRechPres");
    }//GEN-LAST:event_itemRechPresActionPerformed

    private void menuAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccueilActionPerformed
        cardl.show(this.getContentPane(),"cardAccueil");
    }//GEN-LAST:event_menuAccueilActionPerformed

    private void itemAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAccueilActionPerformed
       cardl.show(this.getContentPane(),"cardAccueil");
    }//GEN-LAST:event_itemAccueilActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Pharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Pharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RechExacte;
    private javax.swing.JMenuItem RechPartielle;
    private Pharmacie.graph.Creation creation1;
    private Pharmacie.graph.CreationPres creationPres1;
    private Pharmacie.graph.font font1;
    private javax.swing.JMenuItem itemAccueil;
    private javax.swing.JMenuItem itemCreaPat;
    private javax.swing.JMenuItem itemCreaPres;
    private javax.swing.JMenuItem itemRechPres;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAccueil;
    private javax.swing.JMenu menuPat;
    private javax.swing.JMenu menuPres;
    private Pharmacie.graph.RechExact rechExact1;
    private Pharmacie.graph.RechPart rechPart1;
    private Pharmacie.graph.RechPres rechPres1;
    // End of variables declaration//GEN-END:variables
}
