/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pharmacie.graph;

import Pharmacie.DAO.MedicamentDAO;
import Pharmacie.Metier.Medicaments;
import Pharmacie.Metier.vue_qtite_presc;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author meril
 */
public class RechExacteMedic extends javax.swing.JPanel {

    
    MedicamentDAO medicDAO=null;
    Medicaments medics=null;
    DefaultTableModel dft1 = new DefaultTableModel();
    /**
     * Creates new form RechExacteMedic
     */
    public RechExacteMedic() {
        initComponents();
        dft1.addColumn("idmedoc");
        dft1.addColumn("nom");
        dft1.addColumn("description");
        dft1.addColumn("somme");
        dft1.addColumn("unite");
        jTable1.setModel(dft1);
    }

    public void setMedicamentDAO(MedicamentDAO medicDAO){
        this.medicDAO=medicDAO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblidmedic = new javax.swing.JLabel();
        lblnommedic = new javax.swing.JLabel();
        lbldescmedic = new javax.swing.JLabel();
        lblcodemedic = new javax.swing.JLabel();
        txtidmedic = new javax.swing.JTextField();
        txtnommedic = new javax.swing.JTextField();
        txtdescmedic = new javax.swing.JTextField();
        txtcodemedic = new javax.swing.JTextField();
        btrech = new javax.swing.JButton();
        btmaj = new javax.swing.JButton();
        btsup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnvelrech = new javax.swing.JButton();

        lblidmedic.setText("  Identifiant medicament");

        lblnommedic.setText("  Nom medicament");

        lbldescmedic.setText("  Description medicament");

        lblcodemedic.setText("  Code medicament");

        btrech.setText("Rechercher");
        btrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrechActionPerformed(evt);
            }
        });

        btmaj.setText("Modifier");
        btmaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmajActionPerformed(evt);
            }
        });

        btsup.setText("Supprimer");
        btsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsupActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnvelrech.setText("Nouvele recherche");
        btnvelrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvelrechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btrech)
                        .addGap(153, 153, 153)
                        .addComponent(btmaj)
                        .addGap(129, 129, 129)
                        .addComponent(btsup)
                        .addGap(138, 138, 138)
                        .addComponent(btnvelrech)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblidmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbldescmedic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblnommedic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblcodemedic))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnommedic)
                                .addComponent(txtdescmedic)
                                .addComponent(txtcodemedic, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                            .addComponent(txtidmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblcodemedic)
                            .addComponent(txtcodemedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnommedic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnommedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldescmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescmedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblidmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidmedic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btrech)
                    .addComponent(btmaj)
                    .addComponent(btsup)
                    .addComponent(btnvelrech))
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrechActionPerformed
       String codeRech="";
       String nomRech="";
        try{
           codeRech=txtcodemedic.getText();
           medics=medicDAO.read(codeRech);
           txtdescmedic.setText(medics.getDesc());
           txtidmedic.setText(Integer.toString(medics.getIdmed()));
            txtnommedic.setText(medics.getNom());
            nomRech=txtnommedic.getText();
           JOptionPane.showMessageDialog(this," Medicament trouvé","succès",JOptionPane.INFORMATION_MESSAGE);
       }catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
        
       try{
           //System.out.println(nomRech);
            List<vue_qtite_presc> Vue=medicDAO.rechNom(nomRech);
            int nr = dft1.getRowCount();
            for(int i=nr-1;i>=0;i--)dft1.removeRow(i);
            Vue.stream().map((vue) -> {
                Vector v = new Vector();
                v.add(vue.getIdemedoc());
                v.add(vue.getNom());
                v.add(vue.getDescription());
                v.add(vue.getSomme());
                v.add(vue.getUnite());
               return v;
           }).forEachOrdered((v) -> {       
               dft1.addRow(v);
           });
            JOptionPane.showMessageDialog(this," quantité prescrite de ce medicament trouvé","succès",JOptionPane.INFORMATION_MESSAGE);
       }
       catch(Exception f){
           JOptionPane.showMessageDialog(this,f.getMessage(),"ERREUR PRESCRIPTION ASSOCIE INTROUVABLE",JOptionPane.ERROR_MESSAGE);
           
       }
    }//GEN-LAST:event_btrechActionPerformed

    private void btmajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmajActionPerformed
        try{  
            int numedic=Integer.parseInt(txtidmedic.getText());
            String nom=txtnommedic.getText();
            String desc=txtdescmedic.getText();
            String code=txtcodemedic.getText();
            Medicaments meds=new Medicaments(numedic,nom,desc,code);
            medicDAO.update(meds);
            JOptionPane.showMessageDialog(this," medicament mis à jour","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btmajActionPerformed

    private void btsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsupActionPerformed
       try{
             int numedic=Integer.parseInt(txtidmedic.getText());
             medicDAO.delete(medics);
             txtcodemedic.setText("");
             txtdescmedic.setText("");
             txtidmedic.setText("");
             txtnommedic.setText("");
             JOptionPane.showMessageDialog(this," medicament effacé","succès",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this,e.getMessage(),"ERREUR",JOptionPane.ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btsupActionPerformed

    private void btnvelrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvelrechActionPerformed
        txtcodemedic.setText("");
        txtdescmedic.setText("");
        txtidmedic.setText("");
        txtnommedic.setText("");
    }//GEN-LAST:event_btnvelrechActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmaj;
    private javax.swing.JButton btnvelrech;
    private javax.swing.JButton btrech;
    private javax.swing.JButton btsup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcodemedic;
    private javax.swing.JLabel lbldescmedic;
    private javax.swing.JLabel lblidmedic;
    private javax.swing.JLabel lblnommedic;
    private javax.swing.JTextField txtcodemedic;
    private javax.swing.JTextField txtdescmedic;
    private javax.swing.JTextField txtidmedic;
    private javax.swing.JTextField txtnommedic;
    // End of variables declaration//GEN-END:variables
}
